# Generated by Django 3.1.1 on 2020-12-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valet', '0002_valet_free'),
        ('restro', '0003_restro_name'),
        ('customer', '0002_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('amt', models.IntegerField()),
                ('recv_by_valet', models.BooleanField(default=False)),
                ('recv_by_customer', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ordered', to='customer.customer')),
                ('restro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restro', to='restro.restro')),
                ('valet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valet', to='valet.valet')),
            ],
        ),
    ]
