# Generated by Django 3.1.1 on 2020-12-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_restro_name'),
        ('customer', '0008_auto_20201230_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_under', to='customer.customer')),
                ('restro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restro_under', to='restro.restro')),
            ],
        ),
    ]
