# Generated by Django 3.1.1 on 2020-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
