# Generated by Django 3.1.1 on 2020-12-28 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_for_u', to=settings.AUTH_USER_MODEL),
        ),
    ]
