# Generated by Django 3.1.1 on 2020-12-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_auto_20201228_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='restro',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
