# Generated by Django 3.1.1 on 2020-12-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valet',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
